// I think that social and section header files arent necessary in the section list folder. maybe the actual performcn stats could have their own files...
// ... if the logic is complicated? otherwise teh screen can host the section list for all stats, and we use the component folders and files for the complex ones like modals.
